name: 2fauth
services:
  2fauth:
    image: 2fauth/2fauth:5.4.3
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /2fauth
x-casaos:
  # 主服务名称 （必填），必须与上面 services 中的其中一个服务名称一致 [WebUI 可编辑]
  main: 2fauth
  # Web UI 的索引页面路径 [WebUI 可编辑]
  index: /
  # Web UI 使用的端口号 [WebUI 可编辑]
  port_map: "8000"
  # Web UI 使用的协议，必须是以下值之一： http、https [WebUI 可编辑]
  scheme: http
  # 应用名称，对应前端显示的应用名称信息，支持多语言 （必填）
  title:
    en_US: 2FAuth
  # 应用图标的 URL 地址 [WebUI 可编辑]
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/icon.png
  # 应用缩略图的 URL 地址
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/thumbnail.png
  # 应用截图的 URL 地址
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/2FAuth/screenshot-3.png
  # 应用的简短标语或口号，对应前端商店列表显示的应用标语信息，支持多语言 （必填）
  tagline:
    en_US: A web app to manage your Two-Factor Authentication (2FA) accounts and generate their security codes
    zh_CN: 一个用于管理您的两步验证（2FA）帐户并生成其安全代码的Web应用程序
    ar_SA: تطبيق ويب لإدارة حسابات المصادقة الثنائية (2FA) الخاصة بك وإنشاء رموز أمانها
    de_DE: Eine Web-App zum Verwalten Ihrer Zwei-Faktor-Authentifizierung (2FA) Konten und zum Erstellen ihrer Sicherheitscodes
    es_ES: Una aplicación web para administrar sus cuentas de autenticación de dos factores (2FA) y generar sus códigos de seguridad
    fr_FR: Une application Web pour gérer vos comptes d'authentification à deux facteurs (2FA) et générer leurs codes de sécurité
    hu_HU: Egy webalkalmazás a kétlépcsős hitelesítés (2FA) fiókok kezeléséhez és biztonsági kódjuk generálásához
    it_IT: Un'applicazione web per gestire i tuoi account di autenticazione a due fattori (2FA) e generare i loro codici di sicurezza
    ru_RU: Веб-приложение для управления учетными записями двухфакторной аутентификации (2FA) и генерации их кодов безопасности
    pl_PL: Aplikacja internetowa do zarządzania kontami uwierzytelniania dwuskładnikowego (2FA) i generowania ich kodów bezpieczeństwa
    pt_BR: Um aplicativo da web para gerenciar suas contas de autenticação de dois fatores (2FA) e gerar seus códigos de segurança
    sv_SE: En webbapp för att hantera dina tvåfaktorsautentiserings (2FA) -konton och generera deras säkerhetskoder
    uk_UA: Веб-застосунок для керування обліковими записами двофакторної аутентифікації (2FA) та генерації їх кодів безпеки
  # 应用的描述信息，对应前端显示的应用描述信息，支持多语言 （必填）
  description:
    en_US: 2FAuth is a web based self-hosted alternative to One Time Passcode (OTP) generators like Google Authenticator, designed for both mobile and desktop.
    zh_CN: 2FAuth是一个基于Web的自托管的替代Google Authenticator的一次性密码（OTP）生成器，旨在为移动和桌面设备提供服务。
    ar_SA: 2FAuth هو بديل مستضاف لنفسه لمولدات رمز واحد (OTP) مثل Google Authenticator ، مصممة للجوال وسطح المكتب.
    de_DE: 2FAuth ist eine webbasierte selbst gehostete Alternative zu One Time Passcode (OTP) Generatoren wie Google Authenticator, die für mobile und Desktop-Geräte entwickelt wurde.
    es_ES: 2FAuth es una alternativa autohospedada basada en web a los generadores de códigos de un solo uso (OTP) como Google Authenticator, diseñada para móviles y escritorio.
    fr_FR: 2FAuth est une alternative auto-hébergée basée sur le web aux générateurs de codes à usage unique (OTP) tels que Google Authenticator, conçus pour les appareils mobiles et de bureau.
    hu_HU: A 2FAuth egy webes, önállóan kiszolgáló alternatíva a Google Authenticator egyetlen használatú kódjainak (OTP) generátorának, amelyet mobil és asztali eszközök számára terveztek.
    it_IT: 2FAuth è un'alternativa auto-hosted basata su web ai generatori di codici a tempo singolo (OTP) come Google Authenticator, progettati per dispositivi mobili e desktop.
    ru_RU: 2FAuth - это веб-базовая самохостинговая альтернатива генераторам одноразовых кодов (OTP) вроде Google Authenticator, разработанные для мобильных и настольных устройств.
    pl_PL: 2FAuth to alternatywa samohostowana na podstawie sieci web do generatorów kodów jednorazowych (OTP) takich jak Google Authenticator, zaprojektowana dla urządzeń mobilnych i stacjonarnych.
    pt_BR: 2FAuth é uma alternativa auto-hospedada baseada na web aos geradores de códigos de uso único (OTP) como o Google Authenticator, projetados para dispositivos móveis e desktop.
    sv_SE: 2FAuth är en självhärdad webbaserad alternativ till One Time Passcode (OTP) -genererare som Google Authenticator, utformad för både mobila och skrivbordsenheter.
    uk_UA: 2FAuth - це веб-базова самохостингова альтернатива генераторам одноразових кодів (OTP) на кшталт Google Authenticator, розроблена для мобільних та стільниць пристроїв.
  # 应用的使用提示信息，对应前端显示的使用提示信息 （可选）
  tips: {}
  # 该应用配置文件的作者，对应前端显示的提交者信息 （必填）
  author: CasaOS Team
  # 应用的开发者信息，对应前端显示的开发者信息 （必填）
  developer: Bubka
  # 应用分类，对应前端显示的分类信息 （必填）
  category: Productivity
  # 架构支持列表 （必填），必须包含上面 services 中的所有服务所支持的架构，且必须是以下值之一：amd64、"386"、arm64、arm
  architectures:
    - amd64
    - "386"
    - arm64
    - arm
  # 应用版本信息，对应前端显示的版本信息 (必须填写)
  version: 1.0.0
  # 应用更新日期，对应前端显示的更新日期信息 （可选)
  updateAt: "2024-06-01"
  # 应用版本更新日志，对应前端显示的版本更新日志信息，支持多语言 （可选）
  releaseNotes:
    en_US: Initial release
  # 应用的官方网站地址，对应前端显示的开发者的连接地址 （可选)
  website: http://www.2fauth.com/
  # 应用的源代码仓库地址，对应前端显示的源代码地址信息 （可选)
  repo: http://www.2fauth.com/
  # 应用的支持地址，对应前端显示的 get support 按钮 的连接地址 （可选)
  support: http://www.2fauth.com/
  # 应用的文档地址，对应前端显示的 how we use 的连接地址 （可选)
  docs: http://www.2fauth.com/
