name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge@sha256:36d43ed9711e37fba7a2ab82165c8f3b199398fd6d491c9eeaf289d43850e927
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/jerrykuku/ZimaOS-AppStore@gh-pages/apps/homebridge/assets/icon.svg
  title: Homebridge
  index: /
  port_map: '8581'
  version: latest
