name: duckdns
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns@sha256:71737cabc025d139822146c66529705608155b7e1d13c8b3c6d7948e68400306
    container_name: duckdns
    network_mode: host
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - SUBDOMAINS=subdomain1,subdomain2
    - TOKEN=token
    - UPDATE_IP=ipv6
    - LOG_FILE=false
    volumes:
    - /DATA/AppData/duckdns:/config
    restart: unless-stopped
x-casaos:
  main: duckdns
  icon: https://cdn.jsdelivr.net/gh/jerrykuku/ZimaOS-AppStore@gh-pages/apps/duckdns/assets/icon.svg
  title: duckdns
  index: /
