name: playit-agent
services:
  playit-agent:
    restart: unless-stopped
    image: ghcr.io/mafen/playit-docker:latest
    network_mode: bridge
    container_name: playit-agent
x-casaos:
  main: playit-agent
  icon: https://cdn.jsdelivr.net/gh/jerrykuku/ZimaOS-AppStore@gh-pages/apps/playit-agent/icon.svg
  title:
    en_US: Playit Agent
